#!/bin/bash

set -ex

# ps | grep momo | grep -v momo.run
if [[ $(ps | grep momo_x64 | grep -v 'run') ]]; then
    killall momo_x64
fi

if [[ $(ps | grep momo_arm64 | grep -v 'run') ]]; then
    killall momo_arm64
fi

if [[ $(ps | grep socat) ]]; then
    killall socat
fi

socat pty,echo=0,raw,link=./serial_out  pty,raw,echo=0,link=./webrtc_momo/serial_in &

cd webrtc_momo

./momo_x64 --no-audio-device --no-video-device --serial ./serial_in,9600 test &

# /usr/bin/google-chrome http://127.0.0.1:8080/html/test.html &

# ./momo_x64 sora --signaling-url wss://sora.ikeilabsora.0am.jp/signaling --channel-id ojima-sora --video true --audio false --video-codec-type VP9 --video-bit-rate 1000  --role sendonly --multistream true  &

cd ..

echo "start momo"
