#!/bin/bash
cd webrtc_momo
# ./momo_arm64 --no-audio-device $* sora --signaling-url wss://sora.ikeilabsora.0am.jp/signaling --channel-id ojima-sora --video false --audio false --video-codec-type VP9 --video-bit-rate 1000  --role sendonly --multistream true  &
./momo_arm64 --video-device /dev/video0 --hw-mjpeg-decoder=false --resolution 4K sora  wss://sora.ikeilabsora.0am.jp/signaling ojima-sora --video true --audio true --role sendonly --multistream true  &
cd ..
echo "start sora"
